name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: hugh514
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: hugh514
          author_email: hugh514@users.noreply.github.com
          message: "generate snake animation"
