name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Gera todos os dias à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: hugh514
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate snake animation"
          add: "dist/*.svg"
